pipeline {
   agent any   
   
   tools {
     jdk "Java8" 
   }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean packages'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
